source 'https://github.com/CocoaPods/Specs.git'

target 'eventtracker-ios' do
  pod "eventtracker-ios", :path => "../"
end

target 'Tests' do
  pod "eventtracker-ios", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
